FROM nginx:alpine

LABEL maintainer="bushiwode"
LABEL description="ServerStatus dashboard frontend"

COPY default.conf /etc/nginx/conf.d/default.conf
COPY . /usr/share/nginx/html
RUN rm -f /usr/share/nginx/html/default.conf
